default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: arlymoura
  password: asm123456

development:
  <<: *default
  database: nobank_development

test:
  <<: *default
  database: nobank_test

production:
  <<: *default
  database: nobank_production
